### ISSUE TITLE
ウィジェット1とウィジェット2の幅を同じに

### ISSUE THREAD

**Issue by gouten5010** [jawordpressorg/wordcamp-japan-theme#10]
画像のように、左側が36%になっているので修正
<img width="843" alt="2018-01-16 16 48 06" src="https://user-images.githubusercontent.com/3461188/34977257-2b25b81c-fadd-11e7-952a-d4e7a458e8a9.png">

**Comment by gouten5010** [comment]
ウィジェットの扱いを先に決めるので保留

**Comment by nukaga** [comment]
横並びをやめるということでclose
