### ISSUE TITLE
タイトルが短く、記事本文の先頭に見出しがない場合に本文が回り込まれる

### ISSUE THREAD

**Issue by gouten5010** [jawordpressorg/wordcamp-japan-theme#9]
<img width="830" alt="2018-01-16 16 40 28" src="https://user-images.githubusercontent.com/3461188/34976940-17cf9568-fadc-11e7-920b-f77e09a64074.png">

上記画像のとおり。
回り込ませないようにさせたい

**Comment by nukaga** [comment]
確認できる場合とできない場合があるので、本サイトで確認されるようだったら修正でも良いのでは。（1/16 meeting）

**Comment by nukaga** [comment]
再現しなかったので一旦close
